### ISSUE TITLE
clang-format includes dependent revision

### ISSUE THREAD

**Issue by joker-eph** [google/llvm-premerge-checks#114]
See: https://reviews.llvm.org/D73407

The clang-format patch is about the parent revision.

**Comment by ChristianKuehnel** [comment]
## Problem description:
* When applying a patch, also depedant patches (aka "parent revisions") are fetched from Phabricator and applied on top of some git baseline.
* We're using `git diff` to get the input for clang-tidy and -format. So this diff also contains findings from the parent revision, which we do not want to have.

## Ideas:
* Commit every patch after applying, so that git diff only shows the last one. Not sure if that works with `arc patch`, but with `apply_patch2.py` we could implement such a behavior.

**Comment by metaflow** [comment]
I can confirm that patch also touches mlir/include/mlir/IR/OpImplementation.h and clang-format is doing it's job correctly.

**Comment by metaflow** [comment]
Looking at `apply_patch(2)"

**Comment by metaflow** [comment]
That should be fixed now (I might have broken other things in process but that's a different story)
