### ISSUE TITLE
Disable inline clang-format annotations

### ISSUE THREAD

**Issue by nikic** [google/llvm-premerge-checks#130]
Would it be possible to disable the inline clang-format annotations on Phabricator? As a reviewer, I don't care about them, but they make it quite hard to read diffs.

Bonus points if there's some way to suppress the extra mails all reviewers get from the build results. I don't know if it's possible to achieve that on Phabricator (for example, CI integration on GitHub is always silent and non-intrusive.)

**Comment by ChristianKuehnel** [comment]
I'm not aware of any option to show clang-tidy findings only to the submitter not the reviewer. The only solution I know is to switch off clang-tidy completely. But the goal was to improve our codebase by avoiding new clang-tidy findings to be added, so that would not get us any closer there... 

The mails are created by Phabricator and I'm not familiar with that setup. Did you check your Settings -> Email Preferences?

Concerning GitHub: Yes, I'm a big fan of replacing Phabricator with GitHub pull requests. That would make the CI-setup 10 times simpler.
