### ISSUE TITLE
New llvm contributor unsure how to proceed with certain clang-tidy errors and warnings

### ISSUE THREAD

**Issue by thomasjohns** [google/llvm-premerge-checks#320]
I added the context of "new llvm contributor" in case it might inform a usability issue or additional suggestions for how to respond to clang-tidy errors here: https://github.com/google/llvm-premerge-checks/blob/main/docs/clang_tidy.md.

The pre-merge checks for this https://reviews.llvm.org/D105560 Phabricator review has the following clang-tidy error and warnings (one other error is omitted):
```
/var/lib/buildkite-agent/builds/llvm-project/llvm/lib/Target/ARC/Disassembler/ARCDisassembler.cpp:14:10: error: 'ARC.h' file not found [clang-diagnostic-error]
#include "ARC.h"
         ^
/var/lib/buildkite-agent/builds/llvm-project/llvm/lib/Target/ARC/Disassembler/ARCDisassembler.cpp:110:21: warning: invalid case style for function 'DecodeCCRU6Instruction' [readability-identifier-naming]
static DecodeStatus DecodeCCRU6Instruction(MCInst &, uint64_t, uint64_t,
                    ^~~~~~~~~~~~~~~~~~~~~~
                    decodeCcrU6Instruction
```
The details are provided here aren't too relevant other than to show an instance of a felt ambiguity for how to proceed. The next three paragraphs go into the details if interested.

The missing header file report appears for code in the patch context, but not in the set of lines that changed. Its possible that these appear because `compile_commands.json` don't get linked correctly, but I'm not sure. In any case, it doesn't feel right to add `// NOLINT` to these header includes just to get around the clang-tidy errors. Could this be a bug in the pre-merge checks? I could find other Phabricator reviews with a similar error (e.g. search "lldb/Host/Config.h" here: https://reviews.llvm.org/D105630 (this link may be stale by the time you read this)).

The `DecodeCCRU6Instruction` method has an ambiguity where `decodeCcrU6Instruction` has the correct camel casing, but using a capitol 'D' feels like the more common convention for decode methods in llvm backends (see https://github.com/search?l=&p=2&q=DecoderMethod+repo%3Allvm%2Fllvm-project+path%3Allvm%2Flib%2FTarget&ref=advsearch&type=Code). I think this could be a scenario where the old style unfortunately just stuck, and moving to a mix of `decode*` and `Decode*` or adding an explicit `// NOLINT` is something we have to live with here because of the old style.

I considered adding a rule here https://github.com/google/llvm-premerge-checks/blob/main/scripts/clang-tidy.ignore, but don't see any rules for other specific llvm backends (`llvm/lib/Target/*`), so I wasn't sure about this approach.

My general impression was to treat the failing pre-merge check builds as "blocking" in the sense that we shouldn't commit the patch until the pre-merge check builds pass. Is this correct? Or should the failing pre-merge checks be considered to be something you can ignore, but make sure you know what you are doing when you ignore them?

**Comment by metaflow** [comment]
Hi @thomasjohns ! Thank you for the great report.

> The missing header file report appears for code in the patch context, but not in the set of lines that changed. Its possible that these appear because compile_commands.json don't get linked correctly, but I'm not sure.

It might well be that clang-tidy looks on unchanged lines around. I will check if it's possible to narrow it down to only lines changed.
I believe that we pass compile_commands created by the cmake to clang-tidy (as far as I remember it refuses to run completely if compile_commands are nor present). Maybe you can try to reproduce this by following steps at https://buildkite.com/llvm-project/premerge-checks/builds/46651#dd534b0d-d9c4-40ad-9dd6-896d4a093e65 in a "reproduce build locally" section (maybe it does something wrong? Also note that it will check out already patched version of the LLVM).

As for general question on how to interpret clang-tidy warnings / pre-merge: it's a bit tricky. On one hand it seems to me that existing codebase contains very many "violations" for clang-tidy and benign patch will just surface them. So I would recommend to look at them with a grain of salt. Also note that pre-merge checks are "just for your consideration" and do not block you.
In order to make them produce clear signal I am planning to make clang-tidy warnings to appear but not "fail" the build. What do you think?

**Comment by thomasjohns** [comment]
Thank you for the response @metaflow !

I see the build does symlink compile_commands and attempts to feed clang-tidy-diff a diff with only lines changed with `git diff -U0 ...`. I'll give the "reproduce build locally" a shot and get back to you.

Thanks for the context about the pre-merge checks being "just for your consideration" and non-blocking. I agree that making the clang-tidy warnings appear, but not "fail" the build would help produce a clear signal for this (at least from my "new contributor" perspective).

**Comment by thomasjohns** [comment]
For what it's worth, I do see the same three clang-tidy errors when reproducing the build locally with or without the proper placing of `compiler_commands.json`, except in the latter case there is an additional expected "Error while trying to load a compilation database: ...".

Though this ^ is more of a clang-tidy issue than than an llvm-premerge-checks issue. I will close this since the interpretation of clang-tidy warnings/errors in the llvm review was what I was after. Thanks again for your response.
