### ISSUE TITLE
Seems to be silently failing to patch the changes, and testing HEAD

### ISSUE THREAD

**Issue by sam-mccall** [google/llvm-premerge-checks#56]
See the history on https://reviews.llvm.org/D70357

Hover.cpp is new in that patch, and referenced in CMakeLists, however was omitted in the first snapshot. So the build should definitely fail, but succeeds instead.
The second build succeeds but the ninja logs don't show a compilation of Hover.cpp.o as I'd expect.

My suspicion is that it's not actually patching the changes at all. The logs around that stage show:
```
[Pipeline] sh
+ mkdir -p llvm-premerge-checks
[Pipeline] dir
Running in /mnt/disks/ssd0/agent/workspace/amd64_debian_testing_clang8/llvm-premerge-checks
[Pipeline] {
[Pipeline] git
No credentials specified
Fetching changes from the remote Git repository
Checking out Revision 806e0dd9d23247657e3d43e940617dd4cec89b64 (refs/remotes/origin/master)
Commit message: "upgraded to python3, added dependencies for more projects"
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (arc patch)
[Pipeline] sh
+ python3 /mnt/disks/ssd0/agent/workspace/amd64_debian_testing_clang8/llvm-premerge-checks/scripts/phabtalk/apply_patch.py
 > git rev-parse --is-inside-work-tree # timeout=10
 > git config remote.origin.url https://github.com/google/llvm-premerge-checks.git # timeout=10
Fetching upstream changes from https://github.com/google/llvm-premerge-checks.git
 > git --version # timeout=10
 > git fetch --tags --force --progress -- https://github.com/google/llvm-premerge-checks.git +refs/heads/*:refs/remotes/origin/*
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 806e0dd9d23247657e3d43e940617dd4cec89b64
 > git branch -a -v --no-abbrev # timeout=10
 > git branch -D master # timeout=10
 > git checkout -b master 806e0dd9d23247657e3d43e940617dd4cec89b64
fatal: Could not parse object '0f63ad3c3effa79d6d42b0d96cd9791111133f64'.
Already on 'master'
You have untracked files in this working copy.

  Working copy: /mnt/disks/ssd0/agent/workspace/amd64_debian_testing_clang8/

  Untracked changes in working copy:
  (To ignore this change, add it to ".git/info/exclude".)
    llvm-premerge-checks/

    Ignore this untracked file and continue? [y/N]  Exception 
The program is attempting to read user input, but stdin is being piped from some other source (not a TTY).
(Run with `--trace` for a full exception trace.)
Checking out git hash <built-in function hash>
ERROR: checkout failed, using master instead.
running arc path...
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (CMake)
[Pipeline] sh
+ /mnt/disks/ssd0/agent/workspace/amd64_debian_testing_clang8/llvm-premerge-checks/scripts/run_cmake.sh
```

note suspiciously few details about applying the patch, and an error immediately before the patch should take place.

This would suggest two problems:
 - whatever's causing the error visible in the logs
 - that the system responds to (some) unexpected failures by ignoring and continuing. Is there a bash script that should be running with `-e`?

**Comment by ChristianKuehnel** [comment]
I guess we have a few different issues here:

### (not) failing the build
* The log output of the script is very minimalistic, has broken references and typos. So I fixed the log statements and added more.
* If the apply-patch script can't check out the hash it gets from Phabricator (because the user based the patch on some unknown local commit) it's using the master branch as fallback instead. So this is what the error message is about.
* The `apply_patch.py` script did **no_** check the return code of `arc patch`. That was obviously a bug.
* The `sh` command of the Jenkins pipeline [should fail on non-zero exit codes](https://jenkins.io/doc/pipeline/steps/workflow-durable-task-step/#sh-shell-script). And the python scripts should throw exceptions on errors. All bash scripts are using `set -eu`.

### not patching correctly
* That is difficult to reproduce, as I do not know, which hash/revision Phabricator served with the different commits. To improve debugging, I'm now keeping a copy of the response from Phabricator with each build.

### git hash not found
* It seems that sometimes Phabricator returns a "sourceControlBaseRevision" (=git revision hash) which is not found in the git repository. I'm still trying to understand how that happens. 
* The root cause if obviously, that the process around Phabricator is broken there. Phabricator does not ensure that a diff contains a valid git hash. (This is obviously much better with GitHub pull requests.)
* Can you figure out which git commit your change was based on? 
* Should that commit have been available in the github repo at the time of the build?

**Comment by ChristianKuehnel** [comment]
Applying the patch fails now: https://results.llvm-merge-guard.org/amd64_debian_testing_clang8-112/console-log.txt

**Comment by sam-mccall** [comment]
> It seems that sometimes Phabricator returns a "sourceControlBaseRevision" (=git revision hash) which is not found in the git repository. I'm still trying to understand how that happens.

In this case, this patch was based on a local commit (that I'd sent out for review, modulo some rebasing).
Phabricator allows you to upload any diff you like, the sourceControlBaseRevision is metadata that may be absent or inaccurate. It's not validated against phab's (or any other) version of the repository.

You can mark the dependent changes in Differential, and I hadn't done that here. Arc patch will attempt to do the right thing. Note that in the common case of a revision created by `arc diff`, the first snapshot will initially lack this metadata anyway until the person adds it.

In this case, the best thing to do would be either to show a message that the patch can't be tested because it's not against a commit to master or just silently not do anything (which I'd personally prefer).

> The root cause if obviously, that the process around Phabricator is broken there
It's a different set of tradeoffs - you can review dependent chains in parallel or out-of-order.

**Comment by ChristianKuehnel** [comment]
> In this case, the best thing to do would be either to show a message that the patch can't be tested because it's not against a commit to master or just silently not do anything (which I'd personally prefer).

I agree -- mostly :wink: If we want get better quality on the master branch, we need more test coverage there. To get more tests, we should encourage users to set up their patches so that they can be tested. So I would rather create a custom message for this case. Something like:

```
Warning: Your revision 2937632 could not be applied by arc patch. 

Your revision references git hash 87e56b and this was not found in 
the github repository. Your patch could not be applied to the master
branch either. No tests were executed.

To get your patch tested, see the [user documentation](some link) 
```

**Comment by sam-mccall** [comment]
> To get more tests, we should encourage users to set up their patches so that they can be tested

Tone is important though - the tool shouldn't assume that it's providing more value than a dependent-patch workflow is.

That message looks OK to me, though I think it should should suggest the likely resolution (add dependent revision) and link to the logs.
