### ISSUE TITLE
No builds triggered for D71598 

### ISSUE THREAD

**Issue by ChristianKuehnel** [google/llvm-premerge-checks#84]
There are no builds triggered for https://reviews.llvm.org/D71598.
Figure out why that is and how we can solve it.

Hint: It might be related to submitting it as raw patch, not via arc.

**Comment by kirillbobyrev** [comment]
It seems that this is because I did not use `arc` to create the diff: another patch of mine ([D71880](https://reviews.llvm.org/D71880)) has triggered the builds.

**Comment by kirillbobyrev** [comment]
However, the build that was triggered reports [Clang-Tidy warnings](https://reviews.llvm.org/B42942) that are not relevant to my changes :( Looking at the code [here](https://github.com/google/llvm-premerge-checks/blob/master/scripts/lint.sh#L33) in lint.sh I can see that clang-tidy-diff is invoked, which seems correct, but I'm not sure why this results in unrelated code being reported in my patch.

**Comment by ChristianKuehnel** [comment]
On the clang-tidy warnings: we got a bunch of bug reports on this as well: #91

**Comment by kirillbobyrev** [comment]
I see! Then this bug should probably be "buildbot is not triggered for patches not submitted via `arc`". We might want to simply add a note in documentation, I think that's a reasonable solution. I'm not familiar with the specifics of the bot, so I don't know if this will be hard to trigger it for non-arc submitted patches, too. Another question is whether we actually think it's important and that enough people prefer uploading plain diffs instead of using `arc`. Honestly, I don't know if there is any statistics on that but that might be interesting

**Comment by ChristianKuehnel** [comment]
We still need to understand why the build is not triggered and if the manual upload is really the source fo the problem. 

I would like it also to be triggered for people uploading via the website (or some other API), so that we cover as many patches as we can.

**Comment by ChristianKuehnel** [comment]
Looks like there is not much we can do there, see analysis and comments in #96.
